### ISSUE TITLE
Something missing

### ISSUE THREAD

**Issue by guyutongxue** [umaichanuwu/gi-tex-4.6-full#1]
In TCG, some card faces were not included; or in other words, they were "overwritten" by it's low-quality version. For example, `UI_Gcg_CardFace_Char_Avatar_Tighnari.png` could be this (from ambr.top):

![UI_Gcg_CardFace_Char_Avatar_Tighnari.png](https://api.ambr.top/assets/UI/gcg/UI_Gcg_CardFace_Char_Avatar_Tighnari.png)

but actually we got this:

![UI_Gcg_CardFace_Char_Avatar_Tighnari.png](https://github.com/umaichanuwu/gi-tex-4.6-full/blob/ce5d626d1aa7cd2ebc114f40b10b0f08f22e859d/Texture2D/UI/Gcg/CardFace/Char/Avatar/Tighnari/UI_Gcg_CardFace_Char_Avatar_Tighnari.png?raw=true)

These two picture both have same name `UI_Gcg_CardFace_Char_Avatar_Tighnari.png`, so I guess the "low-quality" version overwrite the "high-quality" ones when extracting assets. We can see under folder `UI/Gcg/CardFace/Char/Avatar`, some character's image are "high-quality", while others are "low quality".

> ![image](https://github.com/umaichanuwu/gi-tex-4.6-full/assets/33127223/65dc131c-2b5d-4df8-9d0c-0d8376aa22c3)  
> A fun fact that if we order names alphabetically, characters name started from A to Q will be high-quality, and R to Z will be low-quality. You can figure this out in the "Size" tab when viewing zip file.

In AssetStudio, if two asset having same name were exported, one will have a postfix like `blah_blah_blah#123456.png`, and the problem was solved. So could you please fix this? Thanks 🤗

**Comment by umaichanuwu** [comment]
done 👍  (06c171c80bfe0512add8d65e32dc453be22693a9)
the script that places the files into folders was skipping duplicates. I've only updated the tcg folder because doing the entire game is long but on the next dump there should be all duplicates as well
